#! /bin/sh

cd ~/tmp
#rm -rf giac-0.6.1
tar xvfz ~/giac/giac-0.8.4.tar.gz
cd giac-0.8.4/debian
cp -f rules.pari rules
cd ..
#export CXXFLAGS='-g -L/usr/local/lib'
export CXXFLAGS='-L/usr/local/lib'
#dpkg-buildpackage -us -uc -rfakeroot
mv debian debiannew
mv debianold debian
mv debiannew debianold
dpkg-buildpackage -rfakeroot
mv debian debiannew
mv debianold debian
mv debiannew debianold
