#!/usr/bin/env bash -x
#
# Script to prepare a clean GIAC source tarball for Sage.  This script is only for the
# package maintainer, not for building GIAC during a Sage install.
#

# Exit on failure
set -e

ORIGDIR=`pwd`
SRC=`pwd`
SAGEPATCHES=$ORIGDIR/sage

# remove unnecessary files
rm -rf $SRC/doc/pari/*.html

rm -f $SRC/doc/*.wasm $SRC/doc/*.js
sed -E -i.bak '/XCASHTML/s/[^ ]*[.](wasm|js)//g' $SRC/doc/Makefile.am

# removing french html doc, but keep keywords, and working makefiles.
# NB: the french html doc is huge and not GPL.
# it is freely redistributable only for non commercial purposes.
cd $SRC/doc/fr
rm -rf [^Mkx]*
rm -rf *.pdf *.eps *.pdf *.png *.cxx *.cas *.jpg *.tex *.stamp *html* cas* *.fig fig*
# repair the build procedure with a minimal Makefile.am
echo -e "EXTRA_DIST = xcasmenu xcasex keywords\n\nlocaldocdir = \$(docdir)/fr \n\n\
dist_localdoc_DATA = xcasmenu xcasex keywords html_mall html_mtt html_vall">Makefile.am
# copy and adjust a minimal Makefile.in
cp ../local/Makefile.in ./
sed -ie 's|localdocdir = $(docdir)/local|localdocdir = $(docdir)/fr|' Makefile.in
sed -ie 's|doc/local|subdir = doc/fr|g' Makefile.in
#
touch html_mall
touch html_mtt
touch html_vall
#

# building giac source tarball for the spkg
cd ../../

# get rid of micropython
rm -rf micropython*
sed -i.bak 's/micropython-[^ ]*//' Makefile.am configure.ac

for a in $SAGEPATCHES/autotools/*.patch; do
    patch -p1 < $a
done
autoreconf -fi

cd ..
# tar -cjf "$OUTPUTFILEBASENAME".tar.bz2 $SRC

# cleaning extracted dir.
cd ..
### rm -rf "$TARGET"

# going back to starting dir
cd "$ORIGDIR"
#$SAGE_ROOT/sage -package update giac "$VERSION"."$VERSIONREV""$PATCHSUFFIX"
#echo "$VERSION"."$VERSIONREV""$PATCHSUFFIX" > build/pkgs/giac/package-version.txt
#$SAGE_ROOT/sage -package fix-checksum giac
